name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        qt_version: [qt5, qt6]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_version: qt5
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_version: qt6
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_version: qt5
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_version: qt6
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        if [[ "${{ matrix.qt_version }}" == "qt5" ]]; then
          sudo apt-get install -y qtbase5-dev
        elif [[ "${{ matrix.qt_version }}" == "qt6" ]]; then
          sudo apt-get install -y qt6-base-dev
        fi

    - name: Install Python on Windows
      if: matrix.os == 'windows-latest'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install aqtinstall on Windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install aqtinstall

    - name: Install Qt on Windows
      if: matrix.os == 'windows-latest'
      run: |
        if [[ "${{ matrix.qt_version }}" == "qt5" ]]; then
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64
        elif [[ "${{ matrix.qt_version }}" == "qt6" ]]; then
          aqt install-qt windows desktop 6.2.4 win64_msvc2019_64
        fi
      env:
        QTDIR: ${{ runner.temp }}/Qt
        PATH: ${{ runner.temp }}/Qt/${{ matrix.qt_version }}/bin:${{ env.PATH }}

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DQt${{ matrix.qt_version }}=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
